<?php


	class AppConstant{

		const PRIMARY = "Application Access Area";
		const APP_ACCESS = "meriGuriya91221";
		const WELLCOME = "<strong>Wellcome to ISSB Preparation</strong> <a href='#' class='pull-right whiteColor' onclick='goLogout()'>Logout</a>";
		const WAT = "../wat/wats.txt";
		const PPDT = "../ppdt/";
		const SCT_URDU_HEAD = 'Sentence Completion Test - URDU';
		const SCT_ENG_HEAD = 'Sentence Completion Test - ENGLISH';

// #############################################################
// # 		application security code
// #           Secret Key for (JS-Encryption & JS_Decryption)
// #############################################################
		const JS_SECRET_KEY = "dnaznisyahl+ayaeshsna107351182-dnn_ecrypt+dnn_decrypt91221";

// ###########################################################
// # 		application security codes
// #			are defined below (PPDT)
// ###########################################################

	const PPDT_UPLOAD_CODE = 'GuriyaDNN91221';
	const PPDT_LIST_IMGS_CODE = 'DNN_Guriya91221';
	const APP_SECURITY_CODE = 'DNN_Meri_Guriya91221';

// ###########################################################
// # 		application flie uploading
// #			are defined below
// ###########################################################	

	const PPDT_PATH = '../ppdt/';
	const SCT_U_PATH = '../sctu/';
	const SCT_E_PATH = '../scte/';

// ###################################################
// #	style for RED text print in BOLD
// ###################################################
	const RED_TXT_START = "<span style=\"color:red; font-weight:bold;\">";
	const RED_TXT_END = "</span>";
// ###################################################
// #	style for white text print in BOLD
// ###################################################
	const WHITE_TXT_START = "<span style=\"color:white; font-weight:bold;\">";
	const WHITE_TXT_END = "</span>";

// ###########################################################
// # 		application all output ( this is only a template ) 
// #			generated by php defined below
// ###########################################################	
/*
* --- 1st argument = ( heading )
* --- 2nd argument = ( tooltip  for cancel )
* --- 3rd argument = ( alert-type / mean's your message )
* --- 4th argument = ( paragraph message initial statement )
* --- 5th argument = ( mentioning any specific name or attr in strong )
* --- 6th argumrnt = ( second half of paragraph message )
* --- 7th argument = ( any special case include content )
*/
	const APP_MESSAGE_TEMPLATE = "<div class='alert alert-danger'>
							<div class='panel panel-warning'>
								<div class='panel-heading'>
									<h2 class='whiteColor'>%s<a href='#' data-dismiss='alert' data-toggle='tooltip' title='%s' class='close pull-right' onclick='getMenues()'>&times;</a></h2>
								</div> <!-- end panel-heading -->
								<div class='panel-body'> <!-- panel-body div -->
									<strong>%s</strong>
										<p>%s <strong>%s</strong> %s</p>
										<p>%s</p>
								</div> <!-- end panel-body div -->
							</div>
						  </div>";

// #########################################################################################
// # 	function names which leads to remove item 
// #		from this app
// #########################################################################################
		const BACK_TO_PPDT = 'removePPDT()';
		const BACK_TO_SCT_URDU = 'removeSCT_URDU()'; 
		const BACK_TO_SCT_ENGLISH = 'removeSCT_ENGLISH()';

// ############################################################
// #	stop writting message 
// #				listed below
// ############################################################

/*
* two arguments are required in this template
*	1st = TEST _ Name 
*	2nd = function name to start test again
*/
		const STOP_WRITTING_NOW = "
			<div class='col-md-10 col-sm-10 col-xs-10'> <!-- 01 div -->
				<div class='panel panel-danger'>
					<div class='panel-heading'>
						<h4><i class='glyphicon glyphicon-alert'></i>
							&nbsp;&nbsp; 
							STOP!
							<a href='#' class='close pull-rignt' data-dismiss='alert' data-toggle='tooltip'
								 onclick='getMenues()' title='Click to Main Menu'>
								 	<i class='glyphicon glyphicon-remove'></i>
							 </a>
						</h4>
					</div> <!-- end panel-heading DIV -->
					<div class='panel-body'>
						<h1>
							<i class='glyphicon glyphicon-info-sign'></i>
							&nbsp;
							%s
						</h1>
						<h3 style='text-align:center;'> Test Time has been finished! </h3>
						<hr />
						<div class='clearfix'></div> <br />
						<ol type='A'>
							<li style='color:black;'><h4>Put your pen down, You are not allowed to write further more.</h4></li>
							<li style='color:black;'><h4>Check your data that you have wrote on your sheet for further analysis.</h4></li>
						    <li style='color:black;'><h4>If you want to attempt test again hit<strong> \"Begin Test\"</strong>.</h4></li>
							<li style='color:black;'><h4>Hit <strong>\"Cancel\"</strong> to main menu.</h4></li>
						</ol>
						<div class='clearfix'></div>
						<br />
						<div class='form-group'>

							<div class='col-md-3 col-sm-3 col-xs-3'>
										<button class='btn btn-success' title='Again start this test' data-toggle='tooltip' 
											type='button' onclick='%s' >
										<i class='glyphicon glyphicon-refresh'> Begin Test</i></button>
							</div>

							<div class='co-md-3 col-sm-3 col-xs-3'>
										<button class='btn btn-warning' title='Click to go back' data-toggle='tooltip' 
											type='button' onclick='getMenues()' >
										<i class='glyphicon glyphicon-remove'> Cancel</i></button>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- 01 div -->
		";
	} // --- end class

?>